### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by Mastermind-sap** [Nova-Striker/Mlon-Eusk#1]
Can you please give us your discord bot token! :laughing: @Nova-Striker

**Comment by Nova-Striker** [comment]
`NF1fd-0sfjkjkf-ajkjf-tumchutiyeho-N0sdfas`

**Comment by Mastermind-sap** [comment]
Noice and my one is:
dkjdf-sdfDDe-TumbhichutiyehoMc-sbsBc

**Comment by subnut** [comment]
It's better if you **delete** this issue...... Discord tokens should not be left public...

**Comment by Mastermind-sap** [comment]
LoL thats not a real token .....read it properly u will find something @subnut

**Comment by Nova-Striker** [comment]
@subnut  Token jara dekho toh😂😂😂

**Comment by subnut** [comment]
Dekha dekha :rofl:
